version: '3.8'
services:
  mkcert:
    image: mkcert
    volumes:
      - $PWD/backend/mkcert/mkcert.sh:/mkcert.sh
      - $PWD/backend/mkcert/certs:/root
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: /bin/sh -c /mkcert.sh
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      endpoint_mode: dnsrr
  tls-gen:
    image: tls-gen
    volumes:
      - $PWD/backend/tlsgen/generate.sh:/generate.sh
      - $PWD/backend/broker/tls:/opt/tls-out
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: /bin/sh -c "/generate.sh $HOSTNAME"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      endpoint_mode: dnsrr
  db:
    image: mongo:6.0.5
    environment:
      - MONGO_INITDB_HOSTNAME=$MONGO_INITDB_HOSTNAME
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
      - MONGO_INITDB_USERNAME=$MONGO_INITDB_USERNAME
      - MONGO_INITDB_PASSWORD=$MONGO_INITDB_PASSWORD
    volumes:
      - $PWD/backend/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - $PWD/backend/db/humboldt-mongo-volume:/data/db
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    command: mongod --quiet
    healthcheck:
      test: echo 'db.runCommand("ping").ok && exit()' | mongosh --quiet
      interval: 10s
      timeout: 20s
      retries: 50
      start_period: 30s
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      endpoint_mode: dnsrr
  broker:
    image: eclipse-mosquitto:2.0.18-openssl
    volumes:
      - $PWD/backend/broker/mosquitto/config:/mosquitto/config
      - $PWD/backend/broker/tls:/opt/tls
    ports:
      - target: 8883
        published: 8883
        protocol: tcp
        mode: host
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "mosquitto_sub -h localhost -p 8883 -t '#' --cafile /opt/tls/ca_certificate.pem --cert /opt/tls/server_certificate.pem --key /opt/tls/server_key.pem -E -i healthcheck | grep -v Error && exit 1 || exit 0",
        ]
      interval: 10s
      timeout: 5s
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      endpoint_mode: dnsrr
  api:
    image: hufapi
    environment:
      - MONGO_INITDB_USERNAME=$MONGO_INITDB_USERNAME
      - MONGO_INITDB_PASSWORD=$MONGO_INITDB_PASSWORD
      - MONGO_INITDB_HOSTNAME=$MONGO_INITDB_HOSTNAME
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
      - MQTT_HOSTNAME=$MQTT_HOSTNAME
      - API_SECRET=$API_SECRET
      - API_SYSTEM_USERNAME=$API_SYSTEM_USERNAME
      - API_SYSTEM_PASSWORD=$API_SYSTEM_PASSWORD
      - NETBOX_API_URL=$NETBOX_API_URL
      - NETBOX_API_TOKEN=$NETBOX_API_TOKEN
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - $PWD/backend/api:/api
      - $PWD/backend/broker/tls:/opt/tls
      - $PWD/backend/mkcert/certs:/opt/certs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: uvicorn app:app --reload --host 0.0.0.0 --port 80 --port 443 --ssl-keyfile /opt/certs/${HOSTNAME}+5-key.pem --ssl-certfile /opt/certs/${HOSTNAME}+5.pem
    healthcheck:
      test: curl --fail --insecure https://localhost:443/healthcheck
      interval: 120s
      timeout: 120s
      retries: 5
      start_period: 5s
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      endpoint_mode: dnsrr
  manager:
    image: hufmanager
    environment:
      - MQTT_HOSTNAME=$MQTT_HOSTNAME
      - MONGO_INITDB_HOSTNAME=$MONGO_INITDB_HOSTNAME
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
      - MONGO_INITDB_USERNAME=$MONGO_INITDB_USERNAME
      - MONGO_INITDB_PASSWORD=$MONGO_INITDB_PASSWORD
      - API_HOSTNAME=$API_HOSTNAME
      - API_ROOT_CA=$API_ROOT_CA
      - API_SYSTEM_USERNAME=$API_SYSTEM_USERNAME
      - API_SYSTEM_PASSWORD=$API_SYSTEM_PASSWORD
      - PJLINK_PASSWORD=$PJLINK_PASSWORD
    volumes:
      - $PWD/backend/manager:/app
      - $PWD/backend/broker/tls:/opt/tls
      - $API_ROOT_CA:$API_ROOT_CA
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: python3 /app/app.py
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      endpoint_mode: dnsrr
  calendar:
    image: hufcalender
    environment:
      - MQTT_HOSTNAME=$MQTT_HOSTNAME
      - MONGO_INITDB_HOSTNAME=$MONGO_INITDB_HOSTNAME
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
      - MONGO_INITDB_USERNAME=$MONGO_INITDB_USERNAME
      - MONGO_INITDB_PASSWORD=$MONGO_INITDB_PASSWORD
    volumes:
      - $PWD/backend/calendar:/app
      - $PWD/backend/broker/tls:/opt/tls
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: python3 /app/app.py
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      endpoint_mode: dnsrr
  knx:
    image: hufknx
    environment:
      - MQTT_HOSTNAME=$MQTT_HOSTNAME
      - API_HOSTNAME=$API_HOSTNAME
      - API_ROOT_CA=$API_ROOT_CA
      - API_SYSTEM_USERNAME=$API_SYSTEM_USERNAME
      - API_SYSTEM_PASSWORD=$API_SYSTEM_PASSWORD
      - KNX_GATEWAY_IP=$KNX_GATEWAY_IP
    volumes:
      - $PWD/backend/knx:/app
      - $PWD/backend/broker/tls:/opt/tls
      - $API_ROOT_CA:$API_ROOT_CA
    ports:
      - target: 3671
        published: 3671
        protocol: tcp
        mode: host
    command: python3 /app/app.py
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      endpoint_mode: dnsrr
networks:
  default:
    external:
      name: mediensteuerung-network
